// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright 2020 NXP.
 */

#ifndef DT_BINDING_RESET_IMX_HDMIMIX_H
#define DT_BINDING_RESET_IMX_HDMIMIX_H

#define IMX_HDMIMIX_HDMI_TX_RESET		0x0
#define IMX_HDMIMIX_HDMI_PHY_RESET		0x1
#define IMX_HDMIMIX_HDMI_PAI_RESET		0x2
#define IMX_HDMIMIX_HDMI_PVI_RESET		0x3
#define IMX_HDMIMIX_HDMI_TRNG_RESET		0x4
#define IMX_HDMIMIX_IRQ_STEER_RESET		0x5
#define IMX_HDMIMIX_HDMI_HDCP_RESET		0x6
#define IMX_HDMIMIX_LCDIF_RESET			0x7

#define IMX_HDMIMIX_RESET_NUM		8

#endif

