// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright 2019 NXP.
 */

#ifndef DT_BINDING_RESET_IMX_AUDIOMIX_H
#define DT_BINDING_RESET_IMX_AUDIOMIX_H

#define IMX_AUDIOMIX_EARC_RESET		0x0
#define IMX_AUDIOMIX_EARC_PHY_RESET	0x1

#define IMX_AUDIOMIX_RESET_NUM		2

#endif

