obj-$(CONFIG_DRM_CDNS_MHDP) += cdns-mhdp-common.o cdns-mhdp-hdmi.o
obj-$(CONFIG_DRM_CDNS_HDMI) += cdns-hdmi-core.o
obj-$(CONFIG_DRM_CDNS_DP) += cdns-dp-core.o
obj-$(CONFIG_DRM_CDNS_AUDIO) += cdns-mhdp-audio.o
obj-$(CONFIG_DRM_CDNS_HDMI_CEC) += cdns-mhdp-cec.o
