# SPDX-License-Identifier: GPL-2.0
#
# Freescale DataPath Acceleration Architecture Gen2 (DPAA2) drivers
#

obj-$(CONFIG_FSL_DPAA2_ETHSW)		+= ethsw/
obj-$(CONFIG_FSL_DPAA2_MAC)		+= mac/
obj-$(CONFIG_FSL_DPAA2_EVB)		+= evb/
