obj-${CONFIG_RM_OTGCONTROL} += otgcontrol.o
otgcontrol-objs := otgcontrol_main.o
otgcontrol-objs += otgcontrol_sysfs.o
otgcontrol-objs += otgcontrol_fsm.o
otgcontrol-objs += otgcontrol_onewire.o
otgcontrol-objs += otgcontrol_charging_ctrl.o
otgcontrol-objs += otgcontrol_dr_mode.o

ccflags-$(CONFIG_RM_OTGCONTROL_DEBUG) += -DDEBUG
