obj-${CONFIG_RM_POGO} += pogo.o
pogo-objs := pogo_main.o
pogo-objs += pogo_sysfs.o
pogo-objs += pogo_kpad.o
pogo-objs += pogo_fsm.o
pogo-objs += pogo_onewire.o
pogo-objs += pogo_charging_ctrl.o
pogo-objs += pogo_fw.o
pogo-objs += pogo_attribute_storage.o

ccflags-$(CONFIG_RM_POGO_DEBUG) += -DDEBUG
